# Generated by Django 4.0.6 on 2022-07-29 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_alter_subcategoria_imagem'),
        ('account', '0004_alter_user_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(choices=[(1, 'muito ruim'), (2, 'ruim'), (3, 'padrão'), (4, 'bom'), (5, 'muito bom')])),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.produto', verbose_name='Produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
