# Generated by Django 4.0.6 on 2022-07-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_review_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='titulo',
            field=models.CharField(default=1, max_length=100, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
