# Generated by Django 4.0.6 on 2022-07-11 19:53

from django.db import migrations
import shop.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='imagem',
            field=stdimage.models.StdImageField(default=1, force_min_size=False, upload_to=shop.models.filename, variations={'thumb': (300, 300, True)}, verbose_name='Imagem'),
            preserve_default=False,
        ),
    ]
