# Generated by Django 4.0.6 on 2022-07-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_categoria_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
