# Generated by Django 4.0.6 on 2022-07-18 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_carrossel_alter_produtos_options_produtos_informacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtos',
            options={'verbose_name': 'Produto'},
        ),
        migrations.CreateModel(
            name='Relacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ManyToManyField(related_name='tags', to='shop.categoria')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.produtos')),
            ],
        ),
    ]
