# Generated by Django 4.0.6 on 2022-07-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_produtos_options_relacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tier',
            field=models.IntegerField(choices=[('produtos principais', 1), ('produtos secundarios', 2)], default=1),
            preserve_default=False,
        ),
    ]
