# Generated by Django 4.0.6 on 2022-07-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_categoria_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaSecundaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='tier',
        ),
        migrations.DeleteModel(
            name='Relacoes',
        ),
        migrations.AddField(
            model_name='categoriasecundaria',
            name='relacionamento',
            field=models.ManyToManyField(related_name='tags', to='shop.categoria'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='subcategoria',
            field=models.ManyToManyField(blank=True, to='shop.categoriasecundaria'),
        ),
    ]
