# Generated by Django 4.0.6 on 2022-07-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_produtos_subcategoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
