# Generated by Django 4.0.6 on 2022-07-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_produtos_nome_alter_produtos_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriasecundaria',
            name='produtos',
            field=models.ManyToManyField(blank=True, related_name='produtos', to='shop.produtos'),
        ),
    ]
