# Generated by Django 4.0.6 on 2022-07-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_produtos_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrossel',
            options={'verbose_name_plural': 'Carrosseis'},
        ),
        migrations.AddField(
            model_name='carrossel',
            name='text',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrossel',
            name='descricao',
            field=models.CharField(max_length=60),
        ),
    ]
