# Generated by Django 4.0.6 on 2022-07-20 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_carrossel_options_carrossel_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrossel',
            old_name='text',
            new_name='texto',
        ),
    ]
