# Generated by Django 4.0.6 on 2022-07-21 19:26

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_rename_text_carrossel_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesquisaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='carrossel',
            name='imagem',
        ),
        migrations.AddField(
            model_name='carrossel',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagem',
            field=stdimage.models.StdImageField(default=1, force_min_size=False, upload_to='', variations={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtos',
            name='pesquisa_tag',
            field=models.ManyToManyField(related_name='tags', to='shop.pesquisatag'),
        ),
    ]
