# Generated by Django 4.0.6 on 2022-07-21 19:54

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_pesquisatag_remove_carrossel_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriasecundaria',
            name='imagem',
            field=stdimage.models.StdImageField(default=1, force_min_size=False, upload_to='', variations={'thumbmail': (400, 400, False)}),
            preserve_default=False,
        ),
    ]
