# Generated by Django 4.0.6 on 2022-07-21 20:18

from django.db import migrations
import shop.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_categoriasecundaria_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='icon',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=shop.models.filename, variations={'thumb': (30, 30, True)}),
        ),
        migrations.DeleteModel(
            name='CategoriaSecundaria',
        ),
    ]
