# Generated by Django 4.0.6 on 2022-07-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_relacionamentosubcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacionamentosubcategoria',
            name='nome',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
