# Generated by Django 4.0.6 on 2022-07-21 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_relacionamentosubcategoria_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='subcategoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.subcategorias'),
            preserve_default=False,
        ),
    ]
