# Generated by Django 4.0.6 on 2022-07-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_produtos_subcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisatag',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
