# Generated by Django 4.0.6 on 2022-07-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_pesquisatag_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacionamentosubcategoria',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
