# Generated by Django 4.0.6 on 2022-07-21 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_rename_grupos_grupo_rename_produtos_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.grupo'),
            preserve_default=False,
        ),
    ]
