# Generated by Django 4.0.6 on 2022-07-21 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_subcategoria_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategoria', to='shop.subcategoria'),
        ),
    ]
