# Generated by Django 4.0.6 on 2022-07-21 21:24

from django.db import migrations
import shop.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_alter_produto_subcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoria',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=shop.models.filename, variations={'thumb': (300, 300, True)}),
        ),
    ]
