# Generated by Django 4.0.6 on 2022-08-02 18:10

from django.db import migrations
import shop.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_alter_subcategoria_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrossel',
            name='imagem',
            field=stdimage.models.StdImageField(default=1, force_min_size=False, upload_to=shop.models.filename, variations={}),
            preserve_default=False,
        ),
    ]
