# Generated by Django 4.0.6 on 2022-08-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_remove_carrossel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='icon',
            field=models.CharField(choices=[('console', 'fas fa-gamepad'), ('jogos', 'fas fa-chess'), ('playstation', 'fab fa-playstation'), ('xbox', 'fab fa-xbox')], max_length=20),
        ),
    ]
