# Generated by Django 4.0.6 on 2022-08-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_categoria_slug_alter_categoria_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='icon',
            field=models.CharField(choices=[('fab fa-playstation', 'playstation'), ('fab fa-xbox', 'xbox')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='icon',
            field=models.CharField(choices=[('fas fa-gamepad', 'console'), ('fas fa-chess', 'jogos')], max_length=20),
        ),
    ]
