# Generated by Django 4.0.6 on 2022-08-11 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_subcategoria_icon_alter_categoria_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.categoria'),
            preserve_default=False,
        ),
    ]
