# Generated by Django 4.0.6 on 2022-08-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_subcategoria_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='color',
            field=models.CharField(choices=[('primary', 'blue'), ('success', 'green'), ('danger', 'red')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
