# Generated by Django 4.0.6 on 2022-08-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_subcategoria_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoria',
            name='icon',
            field=models.CharField(choices=[('fab fa-playstation', 'playstation'), ('fab fa-xbox', 'xbox'), ('fab fa-nintendo-switch', 'nintendo')], max_length=40),
        ),
    ]
