# Generated by Django 4.0.6 on 2022-08-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_alter_subcategoria_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='desconto',
            field=models.IntegerField(blank=True, null=True, verbose_name='Desconto'),
        ),
    ]
